// Create web server
// npm init
// npm install express
// npm install body-parser
// npm install mongoose
// npm install ejs
// npm install express-session
// npm install connect-flash
// npm install express-validator
// npm install passport
// npm install passport-local
// npm install passport-http
// npm install multer
// npm install connect-mongo
// npm install express-messages
// npm install express-validator
// npm install express-session
// npm install express-cookie
// npm install passport-facebook
// npm install passport-twitter
// npm install passport-google-oauth
// npm install passport-linkedin
// npm install passport-github
// npm install passport-instagram
// npm install passport-windowslive
// npm install passport-yahoo
// npm install passport-taobao
// npm install passport-qq
// npm install passport-weibo
// npm install passport-openid
// npm install passport-oauth
// npm install passport-oauth2
// npm install passport-oauth2-refresh
// npm install passport-oauth2-client-password
// npm install passport-oauth2-resource-owner-password
// npm install passport-oauth2-client-password
// npm install passport-oauth2-resource-owner-password
// npm install passport-oauth2-authorization-code
// npm install passport-oauth2-refresh-token
// npm install passport-oauth2-client-password
// npm install passport-oauth2-resource-owner-password
// npm install passport-oauth2-authorization-code
// npm install passport-oauth2-refresh-token
// npm install passport-oauth2-client-password
// npm install passport-oauth2-resource-owner-password
// npm install passport-oauth2-authorization-code
// npm install passport-oauth2-refresh-token
// npm install passport-oauth2-client-password
// npm install passport-oauth2-resource-owner-password
// npm install passport-oauth2-authorization-code
// npm install passport-oauth2-refresh-token
// npm install passport-oauth2-client-password
// npm install passport-oauth2-resource-owner-password
// npm install passport-oauth2-authorization-code
// npm install passport-oauth2-refresh-token
// npm install passport-oauth2-client-password
// npm install passport-oauth2-resource-owner-password
// npm install passport-oauth2-authorization-code
// npm install passport-oauth2-refresh-token
// npm install passport-oauth2-client-password
// npm install passport-oauth2-resource-owner-password
//